on:
  push:
    branches:
      - main

jobs:
  build_base_images:
    runs-on: ubuntu-latest
    name: build Docker Base image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker login
        run: docker login docker.pkg.github.com -u tubone24 -p ${{ secrets.GITHUB_TOKEN }}
      - name: docker build
        run: docker build -t docker.pkg.github.com/tubone24/depcheck_action/base -f Dockerfile_base .
      - name: docker push
        run: docker push docker.pkg.github.com/tubone24/depcheck_action/base
  build_images:
    runs-on: ubuntu-latest
    name: build Docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker login
        run: docker login docker.pkg.github.com -u tubone24 -p ${{ secrets.GITHUB_TOKEN }}
      - name: docker build
        run: docker build -t docker.pkg.github.com/tubone24/depcheck_action/depcheck .
      - name: docker push
        run: docker push docker.pkg.github.com/tubone24/depcheck_action/depcheck
